/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WEBlog.java
 *
 * Created on Jun 27, 2012, 8:09:18 PM
 */
package wlog;
import javax.swing.JOptionPane;
import java.io.*;
import java.util.*;
import java.text.*;
import java.io.*;
import java.util.*;
import java.text.*;
import org.jfree.chart.*;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.*;
import org.jfree.data.general.*;
import javax.swing.*;
/**
 *
 * @author Dayaram
 */
public class WEBlog extends javax.swing.JFrame {
 FileReader f;
    StreamTokenizer s;
    Hashtable h=new Hashtable();
    /** Creates new form WEBlog */
    public WEBlog() {
        initComponents();
       
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        start_dt = new org.freixas.jcalendar.JCalendarCombo();
        end_dt = new org.freixas.jcalendar.JCalendarCombo();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        firefox = new javax.swing.JCheckBox();
        msie = new javax.swing.JCheckBox();
        opera = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(wlog.WlogApp.class).getContext().getResourceMap(WEBlog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        start_dt.setName("start_dt"); // NOI18N

        end_dt.setName("end_dt"); // NOI18N

        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setName("jLabel2"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(end_dt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(start_dt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addGap(127, 127, 127)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start_dt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(end_dt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(58, 58, 58)
                .addComponent(jButton1)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Datewise", jPanel1);

        jPanel2.setName("jPanel2"); // NOI18N

        firefox.setText(resourceMap.getString("firefox.text")); // NOI18N
        firefox.setName("firefox"); // NOI18N

        msie.setText(resourceMap.getString("msie.text")); // NOI18N
        msie.setName("msie"); // NOI18N

        opera.setText(resourceMap.getString("opera.text")); // NOI18N
        opera.setName("opera"); // NOI18N

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opera)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(firefox)
                                .addGap(70, 70, 70)
                                .addComponent(msie))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton2)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firefox)
                    .addComponent(msie))
                .addGap(18, 18, 18)
                .addComponent(opera)
                .addGap(39, 39, 39)
                .addComponent(jButton2)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Browserwise", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(start_dt.getDate().compareTo(end_dt.getDate())==1)
        JOptionPane.showMessageDialog(jTabbedPane1, "Start date should be earlier than End date."); 
        else
           dtwise_rep();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(firefox.isSelected() || msie.isSelected() || opera.isSelected())   
{
    browserwise_rep();
}

    }//GEN-LAST:event_jButton2ActionPerformed
public void browserwise_rep()
{
    String str;
    int Firefox=0,MSIE=0,Opera=0;
    try
        {
            File current=new File("");
            System.out.println(current.getAbsoluteFile());
            f=new FileReader(current.getAbsoluteFile()+"\\weblog.txt");
        }
        catch(Exception e){System.out.println(e);}
        s=new StreamTokenizer(f);
            s.resetSyntax();
            s.wordChars(32, 127);
            s.eolIsSignificant(true);
            try{
        while(s.ttype!=StreamTokenizer.TT_EOF)
        {
            s.nextToken();
            if(s.sval!=null)
            { 
            if(s.sval.toLowerCase().contains("firefox"))
            {
                Firefox++;
            }
            else if(s.sval.toLowerCase().contains("msie"))
            {
                MSIE++;
            }
            else if(s.sval.toLowerCase().contains("opera"))
            {
                Opera++;
            }
            }
        }
            }catch(Exception e){}
            DefaultPieDataset dataset = new DefaultPieDataset();
            if(firefox.isSelected())
                dataset.setValue("Firefox = "+Firefox, Firefox);
            if(msie.isSelected())
                dataset.setValue("MSIE = "+MSIE, MSIE);
            if(opera.isSelected())
                dataset.setValue("Opera = "+Opera, Opera);
            JFreeChart chart = ChartFactory.createPieChart("Sample Pie Chart",dataset,true,true,false);
            ChartFrame frame = new ChartFrame("Browserwise Report", chart);
            frame.pack();
            frame.setVisible(true);
}
    public void dtwise_rep()
    {
        try
        {
            File current=new File("");
            System.out.println(current.getAbsoluteFile());
            f=new FileReader(current.getAbsoluteFile()+"\\weblog.txt");
        }
        catch(Exception e){System.out.println(e);}
        s=new StreamTokenizer(f);
            s.resetSyntax();
            s.wordChars(32, 127);
            s.whitespaceChars(':', ':');
            s.eolIsSignificant(true);
            s.ordinaryChar('[');
            int i=0,flag;
            
            
            DateFormat formatter=new SimpleDateFormat("dd/MMM/yy");
            Date dt,sdate=start_dt.getDate(),edate=end_dt.getDate();
            double data;
            
            try
            {
                while(s.ttype!=StreamTokenizer.TT_EOF)
                {
                    s.nextToken();
                    if(s.ttype!=StreamTokenizer.TT_EOF)
                    {
                        if(s.sval==null)
                        {
                            s.nextToken();
                            
                            dt=(Date)formatter.parse(s.sval);
                            if((sdate.compareTo(dt)==0 || sdate.compareTo(dt)==-1) && (edate.compareTo(dt)==1 || edate.compareTo(dt)==0))
                            {
                                
                                
                                s.ordinaryChar(' ');
                            flag=0;
                            while(flag<6)
                                {
                                    s.nextToken();
                                    if(s.ttype==' ')
                                        flag++;
                                }
                            s.nextToken();
                            if(!(s.sval.equals("-") || s.sval.equals("0")))
                            {
                                data=0.0;
                                if(h.containsKey(dt))
                                {
                                    data=(Double)h.get(dt);
                                }
                                h.put(dt, data+Double.parseDouble(s.sval)/1048576);
                            }
                            s.wordChars(' ', ' ');
                            
                            }
                            while(true)
                            {   
                                s.nextToken();
                                if(s.ttype==StreamTokenizer.TT_EOL)
                                {
                                    break;
                                    
                                }
                            }
                        }
                    }
                }
                
            Calendar c1,c2;
            c1=Calendar.getInstance();
            c1.setTime(sdate);
            c2=Calendar.getInstance();
            c2.setTime(edate);
            DefaultCategoryDataset dataset = new DefaultCategoryDataset();
                while(c1.before(c2))
                {
                dataset.setValue((Double)h.get(c1.getTime()), "Value", c1.get(Calendar.DATE)+"/"+c1.get(Calendar.MONTH)+"/"+c1.get(Calendar.YEAR));
                c1.add(Calendar.DAY_OF_MONTH, 1);
                
                }
                dataset.setValue((Double)h.get(c1.getTime()), "Value", c1.get(Calendar.DATE)+"/"+c1.get(Calendar.MONTH)+"/"+c1.get(Calendar.YEAR));
                JFreeChart chart = ChartFactory.createBarChart("Datewise Data Transferred","Date","Value(In MB)",dataset,PlotOrientation.VERTICAL,true,true,false);
                ChartFrame frame = new ChartFrame("Datewise Data Transferred", chart);
                frame.pack();
                frame.setVisible(true);
            }
            catch(Exception e){System.out.println(e);}
            
            
    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new WEBlog().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.freixas.jcalendar.JCalendarCombo end_dt;
    private javax.swing.JCheckBox firefox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox msie;
    private javax.swing.JCheckBox opera;
    private org.freixas.jcalendar.JCalendarCombo start_dt;
    // End of variables declaration//GEN-END:variables
}
